"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:#313244)\
[$directory](bold fg:#89dceb bg:#313244)\
[ ](bg:#313244)\
$git_branch\
${custom.folder}\
 $character"""

right_format = "$status$time"

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
format = "[$path]($style)"
style = "bold fg:#89dceb bg:#313244"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
disabled = true
symbol = " "

[git_branch]
format = "[](fg:#313244 bg:#89b4fa)[ $symbol$branch ](bold fg:#ffffff bg:#89b4fa)[](fg:#89b4fa)"
style = "bold fg:#ffffff bg:#89b4fa"
symbol = " "

[custom.folder]
command = "echo '󰉋'"
when = "! git rev-parse --git-dir > /dev/null 2>&1"
format = "[](fg:#313244 bg:#89b4fa)[ $output ](bold fg:#ffffff bg:#89b4fa)[](fg:#89b4fa)"
shell = ["zsh", "-c"]

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[character]
success_symbol = "[❯](bold fg:#a6e3a1)"
error_symbol = "[❯](bold fg:#f38ba8)"

[status]
disabled = false
format = "[$symbol ]($style)"
success_symbol = "✓"
symbol = " "
style = "bold fg:#a6e3a1"

[swift]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%H:%M:%S"
style = "bold fg:#cdd6f4"
