"$schema" = 'https://starship.rs/config-schema.json'

format = """
[┌](fg:#6c7086) \
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
[└](fg:#6c7086) \
$character"""

add_newline = true

[username]
show_always = true
style_user = "fg:#a6e3a1"
style_root = "fg:#f38ba8 bold"
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "fg:#f9e2af"
format = '[@](fg:#7f849c)[$hostname]($style)'

[directory]
style = "fg:#74c7ec"
format = '[  ](fg:#6c7086)[$path]($style)'
truncation_length = 3
truncation_symbol = "/.../"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[ $symbol ](fg:#6c7086)[$branch](fg:#cba6f7)'

[git_status]
style = "fg:#f38ba8"
format = '[ $all_status$ahead_behind]($style)'

[cmd_duration]
min_time = 2000
style = "fg:#6c7086"
format = '[ · $duration]($style)'

[character]
success_symbol = "[❯](fg:#a6e3a1)"
error_symbol = "[❯](fg:#f38ba8)"
vicmd_symbol = "[❮](fg:#f9e2af)"
